
<div id="custom-product-message-gift">
    <div class="gift-card">Simple gift card</div>
    <div class="gift-card-main">
        <div class="gift-card-child">
            <label for="reciveName">Name</label>
            <input type="text" name="reciveName" id="reciveName" class="reciveName" placeholder="Enter Name" maxlength="100">
        </div>
        <div class="gift-card-child">
            <label for="message_gift">Message</label>
            <textarea name="giftMessage" id="message_gift" rows="5" placeholder="Enter Message" maxlength="1000"></textarea>
        </div>
    </div>
</div>

